default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: db/my_db
  pool: 5
  timeout: 5000
  username: sa
  host: localhost
  port: 5432
  password: pass

test:
  adapter: postgresql
  database: db/my_db
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: db/my_db
  pool: 5
  timeout: 5000
